//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.26 at 10:22:18 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:7071/ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package localhost._7071.ws;
